name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      if: ${{ github.event_name == 'pull_request' }}
      with:
        ref: 'refs/pull/${{ github.event.pull_request.number }}/merge'

    - name: Checkout code for push
      uses: actions/checkout@v3
      if: ${{ github.event_name != 'pull_request' }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      env:
        PYTHONPATH: ./bin
      run: |
        pytest
